# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealWorld
  pod 'RxSwift',    '~> 3.0'
  pod 'RxSwiftExt'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxDataSources', '~> 1.0'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod 'SnapKit', '~> 3.2.0'
  pod 'Kingfisher', '~> 3.0'

  target 'RealWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealWorldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
